# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8475477341c59a72436332a5fe03e218e2bd7a59ec1acf5a0fa388b9b3ee742eb8c91e2f6cd994036a64437fbe9a63b0a2cbac9af6d18d32dc2896be0615819

test:
  secret_key_base: 3c392c39a9b6af6c60abe8a606a32853290fae92eae0b62b0d9531dbd1dad64efba8a11cba267238b1a14f2de21a959e1e357eac827872d5cd176304b6d5ed4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
